--6-1
SELECT ENAME, UPPER(ENAME), LOWER(ENAME), INITCAP(ENAME)
FROM EMP;
-- UPPER : 모두 대문자
-- LOWER : 모두 소문자
-- INITCAP : 첫글자만 대문자, 나머지 소문자.

--6-2
SELECT *
FROM EMP
WHERE UPPER(ENAME)=UPPER('allen');
--6-3
SELECT *
FROM EMP
WHERE UPPER(ENAME) LIKE UPPER('%allen%');
--6-4
SELECT ENAME, LENGTH(ENAME)
FROM EMP;
--6-5
SELECT ENAME,LENGTH(ENAME)
FROM EMP
WHERE LENGTH(ENAME)>=5;
--6-7
SELECT JOB, SUBSTR(JOB,1,2),SUBSTR(JOB,3,2),SUBSTR(JOB,5)
FROM EMP;
--6-8
SELECT JOB,
        SUBSTR(JOB,-LENGTH(JOB)),
        SUBSTR(JOB,-LENGTH(JOB),2),
        SUBSTR(JOB,-3)
FROM EMP;
SELECT MOD(15,6) FROM DUAL;
--6-27
SELECT EMPNO,HIREDATE,SYSDATE,
        MONTHS_BETWEEN(HIREDATE,SYSDATE) AS MONTHS1,
        MONTHS_BETWEEN(SYSDATE,HIREDATE) AS MONTHS2,
        TRUNC(MONTHS_BETWEEN(SYSDATE,HIREDATE)) AS MONTH3
FROM EMP;
--6-33
SELECT TO_CHAR(SYSDATE,'YYYY/MM/DD HH24:MI:SS')
FROM DUAL;
--6-34
SELECT  SYSDATE,
        TO_CHAR(SYSDATE,'MM') AS MM,
        TO_CHAR(SYSDATE,'MON') AS MON,
        TO_CHAR(SYSDATE,'MONTH') AS MONTH,
        TO_CHAR(SYSDATE,'DD') AS DD,
        TO_CHAR(SYSDATE,'DY') AS DY,
        TO_CHAR(SYSDATE,'DAY') AS DAY
FROM DUAL;

SELECT TO_CHAR(SYSDATE,'WW') FROM DUAL;

--6-38
SELECT SAL,
        TO_CHAR(SAL,'$999,999') AS SAL_$,
        TO_CHAR(SAL,'L999,999') AS SAL_L,
        TO_CHAR(SAL,'999,999.00') AS SAL_1
FROM DUAL;
