/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.30
 * Generated at: 2020-02-06 03:51:42 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.jspexam;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import model.vo.NewsVO;
import java.util.List;

public final class news_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = new java.util.HashSet<>();
    _jspx_imports_classes.add("java.util.List");
    _jspx_imports_classes.add("model.vo.NewsVO");
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSP들은 오직 GET, POST 또는 HEAD 메소드만을 허용합니다. Jasper는 OPTIONS 메소드 또한 허용합니다.");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta charset=\"UTF-8\">\r\n");
      out.write("<title>뉴스 게시판</title>\r\n");
      out.write("<style>\r\n");
      out.write("\r\n");
      out.write("\ttable{\r\n");
      out.write("\t\tmargin : auto;\r\n");
      out.write("\t\ttext-align : center;\r\n");
      out.write("\t\tborder : 1px black solid;\r\n");
      out.write("\t\tborder-collapse : collapse;\r\n");
      out.write("\t}\r\n");
      out.write("\tth,td{\r\n");
      out.write("\t\r\n");
      out.write("\t\tborder : 1px black solid;\r\n");
      out.write("\t\tpadding-left : 10px;\r\n");
      out.write("\t\tpadding-right : 10px;\r\n");
      out.write("\t\r\n");
      out.write("\t}\r\n");
      out.write("\tth{\r\n");
      out.write("\t\r\n");
      out.write("\t\tbackground-color : #666699;\r\n");
      out.write("\t\r\n");
      out.write("\t}\r\n");
      out.write("\ttd#newstitle:hover{\r\n");
      out.write("\t\r\n");
      out.write("\t\tfont-weight : bold;\r\n");
      out.write("\t\r\n");
      out.write("\t}\r\n");
      out.write("\tdiv#total{\r\n");
      out.write("\t\r\n");
      out.write("\t\tborder : 1px black solid;\r\n");
      out.write("\t\twidth : 500px;\r\n");
      out.write("\t\tmargin : auto;\r\n");
      out.write("\t\tbackground-color : silver;\r\n");
      out.write("\t}\r\n");
      out.write("\tspan{\r\n");
      out.write("\t\r\n");
      out.write("\t\tvertical-align : top;\r\n");
      out.write("\t\r\n");
      out.write("\t}\r\n");
      out.write("\r\n");
      out.write("</style>\r\n");
      out.write("</head>\r\n");
      out.write("<body style=\"text-align : center;\">\r\n");
      out.write("<div id=\"total\">\r\n");
      out.write("<h1 style=\"font-family : Times new Roman;\">Jiwon's News Table</h1>\r\n");
      out.write("<hr>\r\n");

	List<NewsVO> list = (List<NewsVO>)request.getAttribute("viewlist");
	NewsVO vo1 = (NewsVO)request.getAttribute("view");
	if(list !=null){

      out.write("\r\n");
      out.write("<table style=\"background-color : white\">\r\n");
      out.write("\r\n");
      out.write("\t<tr>\r\n");
      out.write("\t<th>번호</th>\r\n");
      out.write("\t<th>제목</th>\r\n");
      out.write("\t<th>작성자</th>\r\n");
      out.write("\t<th>작성일</th>\r\n");
      out.write("\t<th>조회수</th>\r\n");
      out.write("\t</tr>\r\n");
      out.write("\t\r\n");
		
		
		
		for(NewsVO vo : list){

      out.write("\r\n");
      out.write("\t\t\t<tr>\r\n");
      out.write("\t\t\t<td class='");
      out.print( vo.getId() );
      out.write('\'');
      out.write('>');
      out.print( vo.getId() );
      out.write("</td>\r\n");
      out.write("\t\t\t<td class='");
      out.print( vo.getId() );
      out.write("' id=\"newstitle\">\r\n");
      out.write("\t\t\t<a href ='/mvc/news?action=read&newsid=");
      out.print( vo.getId() );
      out.write("'>\r\n");
      out.write("\t\t\t");
      out.print( vo.getTitle() );
      out.write("\r\n");
      out.write("\t\t\t</a>\r\n");
      out.write("\t\t\t</td>\r\n");
      out.write("\t\t\t<td class='");
      out.print( vo.getId() );
      out.write('\'');
      out.write('>');
      out.print( vo.getWriter() );
      out.write("</td>\r\n");
      out.write("\t\t\t<td class='");
      out.print( vo.getId() );
      out.write('\'');
      out.write('>');
      out.print( vo.getWritedate() );
      out.write("</td>\r\n");
      out.write("\t\t\t<td class='");
      out.print( vo.getId() );
      out.write('\'');
      out.write('>');
      out.print( vo.getCnt() );
      out.write("</td>\r\n");
      out.write("\t\t\t</tr>\r\n");

		}
		

      out.write("\r\n");
      out.write("</table>\r\n");
      out.write("<hr>\r\n");
 
		if(vo1!=null){
			

      out.write("\r\n");
      out.write("\t\t\t<div id=\"read\">\r\n");
      out.write("\t\t\t<hr>\r\n");
      out.write("\t\t\t<h2>뉴스 내용</h2>\r\n");
      out.write("\t\t\t<form action=\"/mvc/news\" method=\"post\">\r\n");
      out.write("\t\t\t<input type=\"hidden\" name=\"action\" value=\"update\">\r\n");
      out.write("\t\t\t<input type=\"hidden\" name=\"newsid\" value=\"");
      out.print( vo1.getId() );
      out.write("\">\r\n");
      out.write("\t\t\t<input type=\"hidden\" name=\"cnt\" value=\"");
      out.print( vo1.getCnt() );
      out.write("\">\r\n");
      out.write("\t\t\t<span>\r\n");
      out.write("\t\t\t작성자 : <textarea rows=\"1\" cols=\"30\" id=\"m_writer\" name=\"writer\">");
      out.print( vo1.getWriter() );
      out.write("</textarea>\r\n");
      out.write("\t\t\t</span>\r\n");
      out.write("\t\t\t<br>\r\n");
      out.write("\t\t\t제목 :\r\n");
      out.write("\t\t\t<textarea rows=\"2\" cols=\"30\" id=\"m_title\" name = \"title\">");
      out.print( vo1.getTitle() );
      out.write("</textarea>\r\n");
      out.write("\t\t\t<br>\r\n");
      out.write("\t\t\t내용 :\r\n");
      out.write("\t\t\t<textarea rows=\"10\" cols=\"30\" id=\"m_content\"  name=\"content\">");
      out.print( vo1.getContent() );
      out.write("</textarea>\r\n");
      out.write("\t\t\t<br>\r\n");
      out.write("\t\t\t<button id=\"check\" onclick=\"closeread();return false;\">확인</button>\r\n");
      out.write("\t\t\t<input type=\"submit\" id=\"update\" value=\"수정\">\r\n");
      out.write("\t\t\t<button onclick=\"location.href='/mvc/news?action=delete&newsid=");
      out.print( vo1.getId() );
      out.write("';return false;\">삭제</button>\r\n");
      out.write("\t\t\t</form>\r\n");
      out.write("\t\t\t</div>\r\n");

		}

	}

      out.write("\r\n");
      out.write("\r\n");
      out.write("<form action=\"/mvc/news\" method=\"get\">\r\n");
      out.write("\r\n");
      out.write("<select name=\"action\">\r\n");
      out.write("\t<option value=\"search-title\">제목</option>\r\n");
      out.write("\t<option value=\"listwriter\">작성자</option>\r\n");
      out.write("\t<option value=\"search-content\">내용</option>\r\n");
      out.write("\t<option value=\"search-titleandcontent\">제목+내용</option>\r\n");
      out.write("</select>\r\n");
      out.write("<input type=\"text\" name=\"key\">\r\n");
      out.write("<input type=\"submit\" value=\"뉴스 검색\">\r\n");
      out.write("\r\n");
      out.write("</form>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<button onclick=\"displayDiv(1);return false;\">뉴스 작성</button>\r\n");
      out.write("<div id=\"insert\"  style=\"display:none\">\r\n");
      out.write("<hr><h2>뉴스 입력</h2>\r\n");
      out.write("<form method = \"post\" action = \"/mvc/news\">\r\n");
      out.write("<input type=\"hidden\" name=\"action\" value=\"insert\">\r\n");
      out.write("작성자 : <input id=\"i_writer\" type=\"text\"  name=\"writer\" class>\r\n");
      out.write("<br>\r\n");
      out.write("제목 :\r\n");
      out.write("<textarea id=\"i_title\"  rows=\"3\" cols=\"30\" name = \"title\" ></textarea>\r\n");
      out.write("<br>\r\n");
      out.write("<br>\r\n");
      out.write("내용 : <textarea id=\"i_content\" rows=\"10\" cols=\"30\" name=\"content\"></textarea>\r\n");
      out.write("<br>\r\n");
      out.write("<input type = \"submit\" value = \"저장\">\r\n");
      out.write("<input type = \"reset\" value = \"재작성\">\r\n");
      out.write("<button id=\"cancel\" onclick=\"displayDiv(2);return false;\">취소</button>\r\n");
      out.write("</form>\r\n");
      out.write("</div>\r\n");
      out.write("</div>\r\n");
      out.write("<script>\r\n");
      out.write("\tfunction displayDiv(type){\r\n");
      out.write("\t\tvar dom = document.getElementById(\"insert\");\r\n");
      out.write("\t\tif(type == 1){\r\n");
      out.write("\t\t\tdom.style.display='block';\r\n");
      out.write("\t\t}\r\n");
      out.write("\t\telse if(type == 2){\r\n");
      out.write("\t\t\tdom.style.display='none';\r\n");
      out.write("\t\t}\r\n");
      out.write("\t\t\r\n");
      out.write("\t}\r\n");
      out.write("\t\r\n");
      out.write("\tfunction closeread(){\r\n");
      out.write("\t\tdocument.getElementById(\"read\").style.display='none';\r\n");
      out.write("\t}\r\n");
      out.write("\t\r\n");
      out.write("\t\r\n");
      out.write("</script>\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
