--Question 1.
SELECT INITCAP(ENAME) FROM EMP;

--Question 2.
SELECT ENAME, SUBSTR(ENAME,2,3) FROM EMP;

--Question 3.
SELECT LENGTH(ENAME) FROM EMP;

--Question 4.
SELECT LOWER(SUBSTR(ENAME,1,1)), LOWER(SUBSTR(ENAME,LENGTH(ENAME))) FROM EMP;

--Question 5.
SELECT ROUND(3456.78,1) FROM DUAL;

--Question 6.
SELECT TO_CHAR(TRUNC(SAL*50,-2),'999,999') ||''|| '원' FROM EMP;

--Question 7.
SELECT ENAME,NVL2(COMM,'설정','미정'),COMM FROM EMP;
SELECT * FROM EMP;
--Question 8.
SELECT ENAME, DEPTNO,DECODE(DEPTNO,
                            10,' A 부서',
                            20,' B 부서',
                            30,' C 부서',
                            ' 없당') AS 부서명
FROM EMP;

--Question 9.
SELECT ENAME, SAL 
FROM EMP 
WHERE JOB='SALESMAN' 
        AND SAL>=1000;
        
--Quesion 10.
SELECT SYSDATE,SYSDATE+10 FROM DUAL;

--Quesition 11.
SELECT TO_CHAR(SYSDATE,'YYYY"년" MM"월" DD"일" HH24"시" MI"분"') FROM DUAL;

--Question 12.
SELECT ENAME AS "이름", 
       SAL AS "월급여", 
      (200+SAL)*12 AS "연봉"
    FROM EMP;
    
--Question 13.
SELECT ENAME "이름", SAL "월급",
       CASE
        WHEN SAL<1000 THEN '  A'
        WHEN SAL>=1000 AND SAL<2000 THEN '  B'
        WHEN SAL>=2000 AND SAL<3000 THEN '  C'
        WHEN SAL>=3000 AND SAL<4000 THEN '  D'
        ELSE '  E'
    END AS 코드
FROM EMP;
        
--Question 14.
SELECT ENAME AS "이름"
    ,DEPTNO AS "부서번호"
    ,DECODE(DEPTNO,10,'A',20,'B',30,'C',40,'E','F')
FROM EMP;

--Question 15.
SELECT ENAME FROM EMP WHERE ENAME LIKE '_A%';

--Question 16.
SELECT ENAME,
       ROUND(MONTHS_BETWEEN(SYSDATE,HIREDATE)) AS "MONTHS WORKED"
FROM EMP
ORDER BY "MONTHS WORKED";

--Question 17.
SELECT ENAME AS "사원이름",
       TO_CHAR(TRUNC(SYSDATE-HIREDATE))||''||'일' AS "근무일수"
FROM EMP;

--Question 18.
SELECT ENAME, JOB, TO_DATE(HIREDATE,'YYYY/MM/DD')
FROM EMP
WHERE HIREDATE>=TO_DATE('1981-01-01','YYYY/MM/DD') AND HIREDATE<=TO_DATE('1981-12-31','YYYY/MM/DD')
ORDER BY HIREDATE;

SELECT ENAME, JOB, HIREDATE
FROM EMP
WHERE TO_CHAR(HIREDATE,'YYYY')='1981'
ORDER BY HIREDATE;

--Question 19.
SELECT TO_CHAR(TO_DATE('1995 02 04','YYYY/MM/DD'),'DY') FROM DUAL;

--Question 20.
SELECT TRUNC(MONTHS_BETWEEN(SYSDATE,TO_DATE('1995-02-04','YYYY/MM/DD'))) AS MYLIFEMONTH FROM DUAL;

--Question 21.
SELECT ENAME, SAL, NVL(TO_CHAR(COMM),'미정') FROM EMP;

--Question 22.
SELECT ENAME FROM EMP WHERE ENAME LIKE 'A%' AND ENAME NOT LIKE '%N';
SELECT ENAME FROM EMP WHERE SUBSTR(ENAME,1,1)='A' AND SUBSTR(ENAME,-1,1)!='N';
--Question 23.
SELECT ENAME, HIREDATE, ROUND(HIREDATE,'YYYY') FROM EMP;