SELECT * FROM COURSE1;
SELECT * FROM COURSE2;
--1.1
SELECT * FROM COURSE1
INTERSECT
SELECT * FROM COURSE2;

--1.2 -> 서브쿼리 이용
SELECT * FROM
(
    SELECT * FROM COURSE1
    UNION
    SELECT * FROM COURSE2
)
ORDER BY AGE;

--1.3
SELECT NAME FROM COURSE1
MINUS
SELECT NAME FROM COURSE2;

--1.4
SELECT NAME,PHONE FROM(
    SELECT * FROM COURSE2
    MINUS
    SELECT * FROM COURSE1
)
ORDER BY NAME;

--2
SELECT TRUNC(AVG(SAL),2) AS "월급 평균" FROM EMP;

--3
SELECT SUM(COMM) FROM EMP;

--4
SELECT JOB AS "직급명", SUM(SAL) AS "총월급"
FROM EMP
GROUP BY JOB
ORDER BY SUM(SAL);

--5
SELECT NVL2(DEPTNO,TO_CHAR(DEPTNO)||''||'번 부서','미정') AS "부서정보"
        , COUNT(*)||''||'명' AS "직원명수"
FROM EMP
GROUP BY DEPTNO
ORDER BY DEPTNO DESC;

--6 
SELECT CONCAT(TO_CHAR(HIREDATE,'YYYY'),'년') AS "입사년도"
    ,CONCAT(TO_CHAR(COUNT(*)),'명') AS "입사 인원수"
FROM EMP
GROUP BY TO_CHAR(HIREDATE,'YYYY')
ORDER BY COUNT(*) DESC;

--7
SELECT TO_CHAR(SYSDATE,'YYYY"년" MM"월" DD"일 기준으로 "')||''||TO_CHAR(COUNT(*),'99')||''||'명이 근무중입니다.'
FROM EMP;

--8
SELECT JOB AS 직급명, SUM(SAL) AS 총월급
FROM EMP
WHERE JOB!='MANAGER'
GROUP BY JOB
HAVING SUM(SAL)>5000;

--9
SELECT JOB AS "업무명", ROUND(AVG(SAL+NVL(COMM,0)),2) AS "평균월급"
FROM EMP
WHERE DEPTNO=30
GROUP BY JOB;

--10
SELECT TO_CHAR(HIREDATE,'MM"월"'), COUNT(*)
FROM EMP
GROUP BY TO_CHAR(HIREDATE,'MM"월"')
HAVING COUNT(*)>=2
ORDER BY TO_CHAR(HIREDATE,'MM"월"');